### ISSUE TITLE
request non json attachment with Header 'Accept: applicatio/json' should return 406

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/couchbase-lite-android#249]
Here previous tickets:
https://github.com/couchbase/couchbase-lite-android/issues/150
https://github.com/couchbaselabs/cblite-tests/issues/13

https://github.com/couchbaselabs/cblite-tests/blob/master/tests/cbl-document.js#L32

```
ok 17 created docs with inline text attachments
not ok 18 retrieved doc with attachment by http://localhost:8080/cbl-document1/cbl-document1_0/inline.txt with Header 'Accept: applicatio/json' successfully
  ---
    file:   /home/andrey/couchbase_source/cblite-tests/node_modules/coax/node_modules/hoax/lib/hoax-core.js
    line:   21
    column: 11
    stack:  
      - getCaller (/home/andrey/couchbase_source/cblite-tests/node_modules/tap/lib/tap-assert.js:418:17)
      - assert (/home/andrey/couchbase_source/cblite-tests/node_modules/tap/lib/tap-assert.js:21:16)
      - Function.fail (/home/andrey/couchbase_source/cblite-tests/node_modules/tap/lib/tap-assert.js:95:10)
      - Test._testAssert [as fail] (/home/andrey/couchbase_source/cblite-tests/node_modules/tap/lib/tap-test.js:87:16)
      - /home/andrey/couchbase_source/cblite-tests/tests/cbl-document.js:84:27
```

manually

android:
curl -H "Accept: application/json" http://localhost:8080/cbl-document1/cbl-document1_0/inline.txt
Inline text string created by cblite functional 

ios:
curl -H 'Accept: applicatio/json' http://127.0.0.1:59851/cbl-document1/cbl-document1_0/inline.txt
{
  "status" : 406,
  "error" : "not_acceptable"
}
